#!/usr/bin/env bash

NAME=""
CREATE_COMPUTE_RESOURCES="true"

while [[ $# -gt 0 ]]; do
  key="$1"
  case "$key" in
  --skip-compute-resources)
    CREATE_COMPUTE_RESOURCES="false"
    ;;
  --name)
    shift
    NAME="$1"
    ;;
  *)
    echo "Unknown option '$key'"
    exit 1
    ;;
  esac
  shift
done

if [ -z "$NAME" ]; then
  echo "Must provide --name option"
  exit 1
fi

mvn clean &&
  mvn -f pom.xml compile &&
  mvn -f pom.xml package &&
  sam package --template-file template.yml --s3-bucket "$NAME"-dev --output-template-file packaged-template.yml &&
  sam deploy --template-file packaged-template.yml --s3-bucket "$NAME"-dev --stack-name "$NAME"-dev \
    --parameter-overrides EBTrustRole=ClimbAssistElasticBeanstalkTrustRole ResourceNameSuffix=-"$NAME" \
    CreateComputeResources="$CREATE_COMPUTE_RESOURCES" Stage=dev --capabilities CAPABILITY_NAMED_IAM
rm packaged-template.yml
